[profile.release]

# Reduce binary size
codegen-units = 1
lto = true
opt-level = "z"
strip = "symbols"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

# rustup target add x86_64-unknown-linux-musl
# brew install FiloSottile/musl-cross/musl-cross
# TARGET_CC=x86_64-linux-musl-gcc cargo build --release --target x86_64-unknown-linux-musl
